### PR TITLE
Check

### PR DESCRIPTION
**Pull request by Junkie-source**
see if u got the code

### CODE REVIEW

**Comment by Mehnaz2004** [comment]
nope
image

**Comment by Junkie-source** [comment]
ill try once more

**Comment by Mehnaz2004** [comment]
Please update your code to the latest version today im waiting for you to complete this so that i can accept the next pr

**Comment by Junkie-source** [comment]
> Please update your code to the latest version today im waiting for you to complete this so that i can accept the next pr

I'll do it as soon as I reach home

**Comment by Junkie-source** [comment]
Screenshot 2024-10-09 235631
this error is coming

**Comment by Mehnaz2004** [comment]
> Screenshot 2024-10-09 235631 this error is coming

wait a sec

**Comment by Junkie-source** [comment]
ok

**Comment by Mehnaz2004** [comment]
this is your code's ss im getting:

image

i cant see where you have implemented the check box functionality

**Comment by Mehnaz2004** [comment]
have you ever done a pr before?

**Comment by Junkie-source** [comment]
i did but idk whats happening this time t-t sure guide me

**Comment by Mehnaz2004** [comment]
> i did but idk whats happening this time t-t sure guide me

could we do this tommorow around 2 to 3 pm i will guide step by step on meet?

**Comment by Junkie-source** [comment]
i might be at cllg i have pracs t-t 
ill try once

**Comment by Junkie-source** [comment]
ill let u know if i am free early

**Comment by Mehnaz2004** [comment]
> i might be at cllg i have pracs t-t ill try once
ok let me know if u need steps or any other guidance

**Pull request closed without merging**
