### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by Junkie-source**
done just check it once

### CODE REVIEW

**Comment by Junkie-source** [comment]
image
the output

**Comment by Mehnaz2004** [comment]
please provide me with a json file that suits your code for me to check

**Comment by Mehnaz2004** [comment]
the errors are there
image

**Comment by Mehnaz2004** [comment]
Make sure your code is compatible with all the current features of the project including that it is a UI based project or i will be reassigning it soon.

**Pull request closed without merging**
