### PR TITLE
Checklist

### PR DESCRIPTION
**Pull request by Junkie-source**
by mistake made another file sorry the checkbox is empty the checklist has the code so sorry for the inconvenience

### CODE REVIEW

**Comment by Mehnaz2004** [comment]
You have once again submitted empty files, Please make sure to submit your code in the next 24 hours or the issue will be reassigned!

**Comment by Junkie-source** [comment]
howwwww 
Screenshot 2024-10-09 004343
checklist.py on my end is showing the code t-t

**Comment by Mehnaz2004** [comment]
this is what it shows on my end:

image

**Comment by Junkie-source** [comment]
ill do again wait

**Comment by Mehnaz2004** [comment]
> ill do again wait

Okay also a tip ill be closing this pr request due to some issues of those empty files do another pr and dont change the file names like dont make it checkbox or checklist keep the same name as it is in my repo.

**Comment by Junkie-source** [comment]
okay

**Pull request closed without merging**
